[workspace]
members = [
    "crates/gukhanmun-core",
    "crates/gukhanmun-mkdict",
    "crates/gukhanmun-unihan",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Hong Minhe (洪 民憙) <hong@minhee.org>"]
license = "GPL-3.0-only"
homepage = "https://github.com/dahlia/gukhanmun"
repository = "https://github.com/dahlia/gukhanmun"
