allow-branch = ["main", "*.*-maintenance"]
sign-commit = true
sign-tag = true
shared-version = true
dependent-version = "upgrade"
consolidate-commits = true
publish = false
push = false
tag = false
tag-name = "{{version}}"
tag-message = "Release {{version}}"
pre-release-commit-message = "Version bump: {{version}}"
